/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServiceFeesRouteImport } from './routes/service-fees'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VideoConsultRouteImport } from './routes/video-consult'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceFeesRoute = ServiceFeesRouteImport.update({
  id: '/service-fees',
  path: '/service-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoConsultRoute = VideoConsultRouteImport.update({
  id: '/video-consult',
  path: '/video-consult',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/availability': typeof AvailabilityRoute
  '/doctor': typeof DoctorRoute
  '/earnings': typeof EarningsRoute
  '/patients': typeof PatientsRoute
  '/payouts': typeof PayoutsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/service-fees': typeof ServiceFeesRoute
  '/settings': typeof SettingsRoute
  '/video-consult': typeof VideoConsultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/availability': typeof AvailabilityRoute
  '/doctor': typeof DoctorRoute
  '/earnings': typeof EarningsRoute
  '/patients': typeof PatientsRoute
  '/payouts': typeof PayoutsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/service-fees': typeof ServiceFeesRoute
  '/settings': typeof SettingsRoute
  '/video-consult': typeof VideoConsultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/availability': typeof AvailabilityRoute
  '/doctor': typeof DoctorRoute
  '/earnings': typeof EarningsRoute
  '/patients': typeof PatientsRoute
  '/payouts': typeof PayoutsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/service-fees': typeof ServiceFeesRoute
  '/settings': typeof SettingsRoute
  '/video-consult': typeof VideoConsultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/availability'
    | '/doctor'
    | '/earnings'
    | '/patients'
    | '/payouts'
    | '/prescriptions'
    | '/profile'
    | '/reviews'
    | '/service-fees'
    | '/settings'
    | '/video-consult'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/availability'
    | '/doctor'
    | '/earnings'
    | '/patients'
    | '/payouts'
    | '/prescriptions'
    | '/profile'
    | '/reviews'
    | '/service-fees'
    | '/settings'
    | '/video-consult'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/availability'
    | '/doctor'
    | '/earnings'
    | '/patients'
    | '/payouts'
    | '/prescriptions'
    | '/profile'
    | '/reviews'
    | '/service-fees'
    | '/settings'
    | '/video-consult'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AvailabilityRoute: typeof AvailabilityRoute
  DoctorRoute: typeof DoctorRoute
  EarningsRoute: typeof EarningsRoute
  PatientsRoute: typeof PatientsRoute
  PayoutsRoute: typeof PayoutsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceFeesRoute: typeof ServiceFeesRoute
  SettingsRoute: typeof SettingsRoute
  VideoConsultRoute: typeof VideoConsultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-fees': {
      id: '/service-fees'
      path: '/service-fees'
      fullPath: '/service-fees'
      preLoaderRoute: typeof ServiceFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-consult': {
      id: '/video-consult'
      path: '/video-consult'
      fullPath: '/video-consult'
      preLoaderRoute: typeof VideoConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  AvailabilityRoute: AvailabilityRoute,
  DoctorRoute: DoctorRoute,
  EarningsRoute: EarningsRoute,
  PatientsRoute: PatientsRoute,
  PayoutsRoute: PayoutsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceFeesRoute: ServiceFeesRoute,
  SettingsRoute: SettingsRoute,
  VideoConsultRoute: VideoConsultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
